#macro dcw_noone "\\u00ad"

#macro edit_url 0
#macro edit_id 1
#macro edit_token 2
#macro edit_content 3 
#macro edit_username 4
#macro edit_avatar_url 5
#macro edit_embed_use 6
#macro edit_embed_title 7
#macro edit_embed_description 8
#macro edit_embed_url 9
#macro edit_embed_color 10
#macro edit_embed_author_name 11
#macro edit_embed_author_url 12
#macro edit_embed_author_iconUrl 13
#macro edit_embed_image_url 14
#macro edit_embed_image_width 15
#macro edit_embed_image_height 16
#macro edit_embed_footer_text 17
#macro edit_embed_footer_iconUrl 18
#macro edit_embed_thumbnail_url 19
#macro edit_embed_thumbnail_width 20
#macro edit_embed_thumbnail_height 21
#macro edit_embed_video_url 22
#macro edit_embed_video_width 23
#macro edit_embed_video_height 24
#macro edit_embed_provider_name 25
#macro edit_embed_provider_url 26
